import { z } from 'zod';
import { IsoDate } from './primitives.js';

/**
 * Content versioning without a database. The manifest is regenerated by
 * `npm run content:hash`, and a test recomputes the hashes and fails if it is
 * stale — so a content change cannot merge without the version bump appearing
 * in the diff a reviewer is already looking at. Rollback is `git revert`.
 */
export const ManifestSchema = z.object({
  content_version: z.string().regex(/^\d+\.\d+\.\d+$/),
  generated_at: IsoDate,
  records_hash: z.string().regex(/^sha256:[0-9a-f]{64}$/),
  framework_versions: z.record(z.string(), z.string()),
  files: z.array(
    z.object({
      path: z.string(),
      sha256: z.string().regex(/^[0-9a-f]{64}$/),
      record_count: z.number().int().nonnegative(),
    }),
  ),
});
export type Manifest = z.infer<typeof ManifestSchema>;
